/**
 * Shop ID, direct sign-up link and optional Shop Address.
 *
 * The 7-digit Shop ID is generated by the database for New Generation shops
 * only — Legacy shops keep their slug + signup-token links untouched, so this
 * card simply does not appear for them.
 *
 * The Shop Address is optional. When it is filled it decides where the shop
 * appears in municipality discovery; when it is empty discovery falls back to
 * the shop admin's own address, so one operator can run shops in several towns
 * without ever changing their personal address.
 */
import { Copy, MapPin, Store } from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { ProvinceSelect } from "@/components/universe/address-fields";
import { supabase } from "@/integrations/supabase/client";
import { saveShopAddress, shopSignupLink } from "@/lib/shop-directory";

interface ShopRow {
  shop_code: string | null;
  shop_kind: string | null;
  shop_province: string | null;
  shop_city_municipality: string | null;
  shop_barangay: string | null;
  shop_street: string | null;
}

const EMPTY = { province: "", cityMunicipality: "", barangay: "", street: "" };

export function ShopIdentityCard({ ecosystemId }: { ecosystemId: string | null }) {
  const [row, setRow] = useState<ShopRow | null>(null);
  const [address, setAddress] = useState(EMPTY);
  const [saving, setSaving] = useState(false);

  useEffect(() => {
    if (!ecosystemId) return;
    let active = true;
    void supabase
      .from("ecosystems")
      .select("shop_code, shop_kind, shop_province, shop_city_municipality, shop_barangay, shop_street")
      .eq("id", ecosystemId)
      .maybeSingle()
      .then(({ data }) => {
        if (!active || !data) return;
        const r = data as ShopRow;
        setRow(r);
        setAddress({
          province: r.shop_province ?? "",
          cityMunicipality: r.shop_city_municipality ?? "",
          barangay: r.shop_barangay ?? "",
          street: r.shop_street ?? "",
        });
      });
    return () => {
      active = false;
    };
  }, [ecosystemId]);

  if (!ecosystemId || !row?.shop_code) return null;

  const link =
    typeof window === "undefined" ? "" : shopSignupLink(window.location.origin, row.shop_code);

  const copy = async (value: string, what: string) => {
    try {
      await navigator.clipboard.writeText(value);
      toast.success(`${what} copied.`);
    } catch {
      toast.error(`Could not copy the ${what.toLowerCase()}.`);
    }
  };

  const save = async () => {
    setSaving(true);
    try {
      await saveShopAddress(ecosystemId, address);
      toast.success(
        address.province && address.cityMunicipality
          ? "Shop address saved — this shop now appears under that municipality."
          : "Shop address cleared — discovery falls back to your own address.",
      );
    } catch (e) {
      toast.error(e instanceof Error ? e.message : "Could not save the shop address.");
    } finally {
      setSaving(false);
    }
  };

  return (
    <div className="space-y-4">
      <Card className="shadow-[var(--shadow-card)]">
        <CardHeader>
          <CardTitle className="flex items-center gap-2 text-sm">
            <Store className="size-4 text-primary" /> Shop ID &amp; sign-up link
          </CardTitle>
        </CardHeader>
        <CardContent className="grid gap-3 sm:grid-cols-2">
          <div className="space-y-1.5">
            <Label htmlFor="shop-code">Shop ID</Label>
            <div className="flex gap-2">
              <Input
                id="shop-code"
                readOnly
                value={row.shop_code}
                className="font-mono text-base tracking-[0.3em]"
              />
              <Button
                type="button"
                variant="outline"
                size="icon"
                aria-label="Copy Shop ID"
                onClick={() => void copy(row.shop_code ?? "", "Shop ID")}
              >
                <Copy className="size-4" />
              </Button>
            </div>
            <p className="text-[11px] text-muted-foreground">
              Share this with new members — they enter it when signing up.
            </p>
          </div>
          <div className="space-y-1.5">
            <Label htmlFor="shop-link">Direct sign-up link</Label>
            <div className="flex gap-2">
              <Input id="shop-link" readOnly value={link} className="text-xs" />
              <Button
                type="button"
                variant="outline"
                size="icon"
                aria-label="Copy sign-up link"
                onClick={() => void copy(link, "Sign-up link")}
              >
                <Copy className="size-4" />
              </Button>
            </div>
            <p className="text-[11px] text-muted-foreground">
              Opens sign-up with your Shop ID already filled in.
            </p>
          </div>
        </CardContent>
      </Card>

      <Card className="shadow-[var(--shadow-card)]">
        <CardHeader>
          <CardTitle className="flex items-center gap-2 text-sm">
            <MapPin className="size-4 text-primary" /> Shop address (optional)
          </CardTitle>
        </CardHeader>
        <CardContent className="grid gap-3 sm:grid-cols-2">
          <div className="space-y-1.5">
            <Label htmlFor="shop-province">Province</Label>
            <ProvinceSelect
              id="shop-province"
              value={address.province}
              onChange={(v) => setAddress((a) => ({ ...a, province: v }))}
            />
          </div>
          <div className="space-y-1.5">
            <Label htmlFor="shop-city">City / Municipality</Label>
            <Input
              id="shop-city"
              className="h-11"
              placeholder="Enter city or municipality"
              value={address.cityMunicipality}
              onChange={(e) => setAddress((a) => ({ ...a, cityMunicipality: e.target.value }))}
            />
          </div>
          <div className="space-y-1.5">
            <Label htmlFor="shop-barangay">Barangay</Label>
            <Input
              id="shop-barangay"
              className="h-11"
              placeholder="Enter barangay"
              value={address.barangay}
              onChange={(e) => setAddress((a) => ({ ...a, barangay: e.target.value }))}
            />
          </div>
          <div className="space-y-1.5">
            <Label htmlFor="shop-street">Street (optional)</Label>
            <Input
              id="shop-street"
              className="h-11"
              placeholder="Enter street"
              value={address.street}
              onChange={(e) => setAddress((a) => ({ ...a, street: e.target.value }))}
            />
          </div>
          <div className="sm:col-span-2 flex flex-wrap items-center gap-3">
            <Button onClick={() => void save()} disabled={saving}>
              {saving ? "Saving…" : "Save shop address"}
            </Button>
            <Button
              variant="outline"
              disabled={saving}
              onClick={() => {
                setAddress(EMPTY);
                void saveShopAddress(ecosystemId, EMPTY)
                  .then(() =>
                    toast.success("Shop address cleared — discovery uses your own address."),
                  )
                  .catch((e: Error) => toast.error(e.message));
              }}
            >
              Clear
            </Button>
            <p className="text-[11px] text-muted-foreground">
              Leave empty to use your own address for municipality discovery.
            </p>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
