/**
 * Download-state rules for the Admin portal-template builder.
 *
 * Kept out of the component so the exact click path and the refresh behaviour
 * that previously disabled the Download button can be tested directly.
 */
import { downloadTextFile, type DownloadResult } from "./download-file";

export interface PortalArtifact {
  fileName: string;
  html: string;
}

/**
 * A status refresh must never throw away the artifact the admin just
 * generated: that is what disconnected the Download button from its bytes.
 */
export function resolveGeneratedAfterRefresh<T>(
  current: T | null,
  opts?: { keepGenerated?: boolean },
): T | null {
  return opts?.keepGenerated ? current : null;
}

export interface PortalDownloadOutcome {
  ok: boolean;
  fileName: string;
  /** Object URL for a visible fallback link when the click was blocked. */
  fallback: { url: string; fileName: string } | null;
  error?: string;
}

/** Downloads the exact generated bytes. Never regenerates or alters them. */
export function runPortalDownload(
  artifact: PortalArtifact | null,
  download: (html: string, fileName: string) => DownloadResult = downloadTextFile,
): PortalDownloadOutcome {
  if (!artifact) {
    return { ok: false, fileName: "", fallback: null, error: "Generate the portal page first." };
  }
  const res = download(artifact.html, artifact.fileName);
  if (res.ok) return { ok: true, fileName: res.fileName, fallback: null };
  return {
    ok: false,
    fileName: res.fileName,
    fallback: res.url ? { url: res.url, fileName: res.fileName } : null,
    error: res.error ?? "Use the direct link below to save the page.",
  };
}
