import { describe, expect, it } from "vitest";
import { resolveGeneratedAfterRefresh, runPortalDownload } from "../portal-download";
import { portalArtifactResponse } from "../portal-artifact-download.server";

const artifact = { fileName: "shop-portal.html", html: "<html>portal</html>" };

describe("portal download state", () => {
  it("keeps the freshly generated artifact when the status is refreshed", () => {
    expect(resolveGeneratedAfterRefresh(artifact, { keepGenerated: true })).toBe(artifact);
  });

  it("clears the artifact when the portal, theme or features change", () => {
    expect(resolveGeneratedAfterRefresh(artifact)).toBeNull();
  });

  it("downloads the exact generated bytes and file name", () => {
    const seen: Array<{ html: string; fileName: string }> = [];
    const out = runPortalDownload(artifact, (html, fileName) => {
      seen.push({ html, fileName });
      return { ok: true, fileName, url: "blob:x" };
    });
    expect(seen).toEqual([{ html: artifact.html, fileName: artifact.fileName }]);
    expect(out).toEqual({ ok: true, fileName: "shop-portal.html", fallback: null });
  });

  it("exposes a visible fallback link when the browser blocks the click", () => {
    const out = runPortalDownload(artifact, (_h, fileName) => ({
      ok: false,
      fileName,
      url: "blob:blocked",
      error: "blocked by browser",
    }));
    expect(out.ok).toBe(false);
    expect(out.fallback).toEqual({ url: "blob:blocked", fileName: "shop-portal.html" });
  });

  it("does nothing when no artifact exists yet", () => {
    expect(runPortalDownload(null).ok).toBe(false);
  });

  it("streams exact persisted bytes as a browser attachment", async () => {
    const html = "<!doctype html><html><body>Exact café bytes</body></html>";
    const response = portalArtifactResponse(html, "../shop portal.html");
    expect(response.status).toBe(200);
    expect(response.headers.get("content-type")).toBe("text/html; charset=utf-8");
    expect(response.headers.get("content-disposition")).toContain('attachment; filename="shop portal.html"');
    expect(Number(response.headers.get("content-length"))).toBe(new TextEncoder().encode(html).byteLength);
    expect(await response.text()).toBe(html);
  });
});
